spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/users/**, /v1/auth/**, /internal/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v1/products/**, /v1/categories/**
        - id: auction-service
          uri: lb://auction-service
          predicates:
            - Path=/v1/auctions/**, /internal/bids/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/v1/wallets/**, /internal/wallets/**, /internal/deposits/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/v1/chatrooms/**
        - id: alert-service
          uri: lb://alert-service
          predicates:
            - Path=/v1/alerts/**, /internal/v1/alerts/**

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

